db_username: "postgres"
db_password: "1"
db_host: "localhost"
db_name: "attendances"
default_lang: "uz"
port: 5432
disable_tls: true
base_url: "https:localhost:8080/api/v1"
jwt_key: "attendancePanel"
