db_username: "postgres"
db_password: "password1"
db_host: "18.179.29.110"
db_name: "attendances"
default_lang: "uz"
port: 5432
disable_tls: true
base_url: "https:18.179.29.110:8080/api/v1"
jwt_key: "attendancePanel"
