db_username: "postgres"
db_password: "pasword1"
db_host: "43.207.0.156"
db_name: "attendances"
default_lang: "uz"
port: 5432
disable_tls: true
base_url: "http://43.207.0.156:8080/api/v1"
jwt_key: "attendancePanel"
