# version: '3'
# services:
#   backend:
#      build: "./"
#      restart: always
#      container_name: attendance-app
#      labels:
#        logging: "promtail"
#        logging_jobname: "containerlogs"
#      ports:
#         - "8080:8080"
#      networks:
#        - app
# networks:
#   app:
#     external: true

version: '3'
services:
  backend:
    build: "./"
    restart: always
    container_name: attendance-app
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - "8080:8080"
    networks:
      - app
    environment:
      DB_HOST: "127.0.0.1"
      DB_PORT: 5432
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password1"
      DB_NAME: "attendances"

networks:
  app:

volumes:
  db_data:
