name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Faqat main branchdagi o'zgarishlar uchun

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Repository kodini yuklash
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker CLI sozlash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub'ga login qilish
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker imageni build va push qilish
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/attendance:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Bu bosqichni oldingi build tugagandan keyin ishlaydi

    steps:
      # SSH orqali serverga ulanib yangi Docker imageni pull va run qilish
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/attendance:latest
            docker stop attendance-backend || true
            docker rm attendance-backend || true
            docker run -d --name attendance-backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/attendance:latest
            docker restart attendance-backend